"""Add loan table with relations to user and book

Revision ID: 951ffd7ea844
Revises: 
Create Date: 2024-11-19 12:47:49.500115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951ffd7ea844'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('loan_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('return_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_loan_book_id', 'book', ['book_id'], ['id'])
        batch_op.create_foreign_key('fk_loan_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('title')
        batch_op.drop_column('year')
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_loan_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_loan_book_id', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('return_date')
        batch_op.drop_column('loan_date')
        batch_op.drop_column('book_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
